version: '3.8' # not really needed

services:
  web:
    build:
      context: ./web-service
    container_name: recipe-management-web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production

  redis:
    image: redis:latest
    container_name: recipe-management-redis
    volumes:
      - ./data/redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

volumes: # not really needed
  redis_data:
    driver: local